### PR TITLE
SetGas, PushGas, and asm renaming

### PR DESCRIPTION
**Pull request by RachelFranks**
Made instruction naming consistent with the Arbitrum design spec.
Removed SetGas and PushGas asm in favor of new expressions.

### CODE REVIEW

**Review by edfelten — APPROVED** [review]
Looks good.  I'm approving this, but let's talk about how and when to merge it.

**Review by edfelten — CHANGES_REQUESTED** [review]
I think we need to make the setgas and gets language-level functions impure.

**Comment by RachelFranks** [comment]
> I think we need to make the setgas and gets language-level functions impure.

Just made the changes: SetGas(_) and GetGas() make a function impure.

**Review by edfelten — APPROVED** [review]
Looks good.

**Pull request merged**
